server:
    port: 8090
    servlet:
        context-path: /demo

#集成hibernate
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        new_generator_mappings: false
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: testUser
    password: Tu123456
# 默认reis配置------------------------------------------------
#  分布式事务+redis缓存配置
#  session:
#    #告诉spring开启redis方式的session存储 或者在启动类上加@EnableRedisHttpSession
#    store-type: redis
#    timeout: 3600s
#    redis:
#      flush-mode: on_save
#      namespace: spring:session
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 5000ms
# 默认reis配置------------------------------------------------

# 自定义reids配置------------------------------------------------
redis:
  mode: standalone
  host: 127.0.0.1
  port: 6379
  password:
  usePool: true
  database: 4
  maxTotal: 50
  maxIdle: 10
  minIdle: 20
  keepAliveSeconds: 1000
  queueCapacity: 120
  maxPoolSize: 5
  corePoolSize: 2
  maxWaitMillis: 3000
  testOnBorrow: true
  maxInactiveIntervalInSeconds: 1800
  defaultExpiration: 360000
  master:
  sentinelHostAndPorts:
  clusterNodes:
  session:
    mode: standalone
    host: localhost
    port: 6379
    password:
    usePool: true
    database: 4
    maxTotal: 20
    maxIdle: 10
    maxWaitMillis: 3000
    testOnBorrow: true
    maxInactiveIntervalInSeconds: 1800
    defaultExpiration: 36000
    clusterNodes:
    master:
    sentinelHostAndPorts:

# 自定义reids配置------------------------------------------------

